# Generated by Django 4.0.4 on 2022-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
