# Generated by Django 4.0.4 on 2022-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdule', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer',
            old_name='ch',
            new_name='channel_id',
        ),
        migrations.AddField(
            model_name='streamer',
            name='playlists_id',
            field=models.TextField(null=True),
        ),
    ]
