# Generated by Django 4.0.4 on 2022-06-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdule', '0003_rename_ch_streamer_channel_id_streamer_playlists_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamer',
            name='playlists_id',
        ),
    ]
